---

- name: Copy new RPi 'hosts' file
  ansible.builtin.copy:
    src: ../../../files/hosts-new
    dest: /etc/cloud/templates/hosts.debian.tmpl

- name: Restart network service
  ansible.builtin.service:
    name: systemd-networkd
    state: restarted

...