---

- name: Copy new RPi 'hosts' file
  ansible.builtin.copy:
    src: ../../../files/ubuntu22.04/hosts-new
    dest: /etc/hosts

- name: Restart network service
  ansible.builtin.service:
    name: systemd-networkd
    state: restarted

...