---

- name: Copy (revert) RPi 'hosts' file to original
  ansible.builtin.copy:
    src: ../../../files/ubuntu22.04/hosts-original
    dest: /etc/hosts

- name: Restart network service
  ansible.builtin.service:
    name: systemd-networkd
    state: restarted

...