---

- hosts: all
  become: yes

  tasks:
  - name: Ensure Ubuntu HOSTS file is set.
    include_tasks: "{{ playbook_dir }}/kubernetes/00-environment-prereqs/hosts/playbook-set-ubuntu-hosts-file.yml"

...