---

- hosts: all
  become: yes

  tasks:
  - name: Ensure RPI HOSTS file is reset to Default.
    include_tasks: "{{ playbook_dir }}/kubernetes/00-environment-prereqs/hosts/playbook-reset-rpi-hosts-file.yml"

...