---

- name: Ensure Googles apt repository is enabled
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Ensure kubernetes repository is available
  ansible.builtin.apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes

- name: Ensure the Kubernetes packages are installed.
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - kubelet=1.23.4-00
      - kubeadm=1.23.4-00
      - kubectl=1.23.4-00
    state: present

- name: Prevent packages from being upgraded (kubeadm, kubelet and kubectl) - Mark as Hold at v1.23.4-00.
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
    - containerd

- name: Ensure the kubelet and containerd services have restarted and set to start on boot.
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - kubelet
    - containerd

...