---

- name: Allow 'hold' packages to be removed (kubeadm, kubelet and kubectl).
  dpkg_selections:
    name: "{{ item }}"
    selection: install
  loop:
    - kubelet
    - kubeadm
    - kubectl
    - containerd

- name: Ensure containerd is uninstalled.
  ansible.builtin.apt:
    name: containerd
    state: absent

- name: Ensure containerd config file does not exist.
  ansible.builtin.file:
    path: /etc/containerd/config.toml
    state: absent

- name: Ensure containerd prereqs are removed.
  community.general.modprobe:
    name: '{{ item }}'
    state: absent
  with_items:
    - overlay
    - br_netfilter

- name: Ensure containerd.conf does not exist.
  ansible.builtin.file:
    path: /etc/modules-load.d/containerd.conf
    state: absent

- name: Ensure containerd sysctl params file does not exist.
  ansible.builtin.file:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    state: absent

- name: Ensure sysctl param changes are applied.
  shell: sysctl -p --system

...